### ISSUE TITLE
Research file upload possibilities

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/foodsaving-backend#137]
We need file uploads at least for profile pictures. Research a nice way that would ideally also allow showing progress.

**Comment by NerdyProjects** [comment]
There is http://tus.io/ which is a HTTP protocol extension which is (as of now - source: tus.io js client) compatible with 85% of the users.

It allows resumable uploads and client side progress. The server side for now is a go server, we might use that or create and supply a python server / django application.

A not-tus-compliant upload could be done to the same server so offering a normal POST request as fallback with little adjustments on both server and client side.

**Comment by nicksellen** [comment]
For the frontend part https://github.com/danialfarid/ng-file-upload looks pretty good.

**Comment by tiltec** [comment]
Not needed right now. Would be nice to have, but the page is usable without.
