### ISSUE TITLE
Track changes on database fields

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#171]
Tracking of field values seems important to me. Usage:
- deliver logs _who did what_
- treat changes as events and deliver notifications: _hey, John Doe changed the topic of our conversation_
- offer undo functionality to users

We can use a wealth of Django packages for that:
https://github.com/etianen/django-reversion (seems to be the best one)
https://github.com/treyhunner/django-simple-history
https://github.com/swisscom/cleanerversion

**Comment by nicksellen** [comment]
I would not think about this before MVP is launched.

**Comment by TPei** [comment]
I believe listening to change events to trigger notifications is usually achieved by using Django's built-in [Signals](https://docs.djangoproject.com/en/1.9/topics/signals/).
For example you can subscribe to [pre_save](https://docs.djangoproject.com/en/1.9/ref/signals/#pre-save) and [post_save](https://docs.djangoproject.com/en/1.9/ref/signals/#post-save) events.

**Comment by tiltec** [comment]
Not needed right now. Would be nice to have, but the page is usable without.
