### ISSUE TITLE
Respond with Unauthorized by default when unauthorized

### ISSUE THREAD

**Issue by Sneezoo** [yunity/foodsaving-backend#204]
Issue to find out which endpoint should be and which ones should not be not accessible by unauthorized users

**Comment by tiltec** [comment]
@Sneezoo I don't get it - which endpoint?

**Comment by Sneezoo** [comment]
See updated description.
My suggestion is to answer with unauthorized by default but disable that for specific ebdpoints like the signup and login endpoints

**Comment by tiltec** [comment]
#175 I already went through most of the endpoints to deny access if you shouldn't have the rights.
Is there a specific endpoint that you have in mind? @sneezoo

**Comment by tiltec** [comment]
@Sneezoo Can I close this?
