### ISSUE TITLE
Conversations: multiple improvement requests

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-backend#221]
1. **filter current user from participants list**
on the frontend in most cases it is necessary to remove the current user from the participants array.
so far i can't imagine a case where it is useful to have it in the response and it would make the frontend cleaner
2. **smaller responses**
 `/api/conversations/` should not have all messages from all conversations (getting a lot), just the most recent one for previews
3. **type field redundant?** _(ONE_ON_ONE / MULTICHAT)_
  i would determine the type always by the count of participants and not by an extra field.

**Comment by tiltec** [comment]
Hm.. I don't see immediate action to change any of them, do you agree?

As clarification:

1. there might be a hypothetical situation where non-participants can access a chat.. I don't want special API cases for that. I suggest to filter it out in a frontend service.
2. that should be added, but probably only when we have basic functionality and it starts to be more than 1 MB
3. ONE_ON_ONE are private messages, MULTICHAT are group chats. The thing is that you don't want to have your private chat history shared when you add another person to the chat. So we make a difference between a private and a group chat (which can also have two participants at a given time, so you won't be able to guess from the number).

**Comment by alangecker** [comment]
okay, all 3 points make sense! :+1: 

**last question:** _(answer can close)_
Is it possible to have more `ONE_TO_ONE` chats with the same person? if not: does it make sense to have a topic for that conversation?
does not require any change on the backend, i would just hide it on the frontend

**Comment by tiltec** [comment]
No, it should not be possible to create more than one ONE_TO_ONE chat with the same person. Makes perfect sense to hide the topic!
