### ISSUE TITLE
Conversations: read/unread state

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-backend#222]
essential for a 'new messages' notification/count in the topbar

probably the easiest solution would be:
- an readBy[] array for each conversation
- `GET /conversations/:id/read` adds the current userId to this array
- on new message
   * empty array
   * mark as read for author

**Comment by tiltec** [comment]
I see that is will be necessary, your solution seems reasonable. Accepting pull requests ;)

But seriously, I think we can go for a while without marking messages as unread. More generally, we should think about notification services in future (email, app, facebook...)

**Comment by tiltec** [comment]
Conversations will get redesigned.
