### ISSUE TITLE
Check if default permission_classes is always defined and returned

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#232]
Otherwise list_route and detail_route permission classes are not active

**Comment by yogesh-kamble** [comment]
Do we need to add default permissions classes in settings or for each route we have to add permission_classes

**Comment by tiltec** [comment]
Sorry, this issue needs more explanation. This is only relevant if `permission_classes` is used with list/detail_route decorators. Then `get_permissions()` needs to return the default permission class. I *think* this is the case in our codebase, but I didn't verify yet. This is what the issue is about.

**Comment by yogesh-kamble** [comment]
> @list_route(
        methods=['POST'],
        permission_classes=(IsAuthenticated,)
    )
    def resend_verification(self, request, pk=None):
        "resend verification mail"
        if request.user.mail_verified:
            return Response(status=status.HTTP_400_BAD_REQUEST,
                            data={'error': 'Already verified'})
        request.user.send_new_verification_code()
        return Response(status=status.HTTP_204_NO_CONTENT, data={})

so for above route get_permissions should return the default permissions which is defined in settings.py as well as "IsAuthenticated" which is defined in here ?

**Comment by tiltec** [comment]
By `default`, I mean `self.permission_classes`. Have a look at any `get_permission_classes` method in our codebase. I don't take the value from settings.py into account.

**Comment by yogesh-kamble** [comment]
created this pull request https://github.com/yunity/foodsaving-backend/pull/306 
please review it.. if changes are correct then will make same changes in other get_permission_classes method.

**Comment by tiltec** [comment]
Seems no change is necessary.
