### ISSUE TITLE
[stuff] Tilmann's backend notepad

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#250]
- backend: normalize username or other potential search fields (unicodedata.normalize(NFKC))

- backend: move signal handlers where they belong, move signals to signals.py

**Comment by yogesh-kamble** [comment]
I can work on this

**Comment by tiltec** [comment]
Both are not urgent, maybe the second one is a nice refactoring step. Where do you usually define Signals and put the signal handlers?
