### ISSUE TITLE
Thoughts about conversations/wall

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#254]
As we probably won't implement our own chat soon, we could remove the conversations app from the backend. This allows us also to remove redis from the dependencies.

Opinions?

**Comment by djahnie** [comment]
Wasn't there the idea to use the conversations like a bulletin board in the store details? Or will the communication between foodsavers who pick-up at the same store now work solely via feedback from past pick-ups and the desciption? (And at other places we don't care about, of course...^^)

**Comment by D0nPiano** [comment]
I would still like to integrate some sort of chat - so I'd only get rid of it if we find a better solution.

**Comment by Sliverriver** [comment]
what about if i want to give a feedback without having a pickup ? it would be nice to have something like the "pinnwand" feature.

**Comment by tiltec** [comment]
For a Pinnwand/pinboard/wall, I would consider a rewrite of the conversations app. A pinboard doesn't need to manage participants, because they are given by the group membership.

I'm thinking about a way how to use one endpoint for group and store walls. We could try to add a `get_members()` method on the store and the group that returns all members and can be used for permission checking.

Alternatively, we could implement a `group` reference into a `wall` model like this:

```py
class Wall(model):
  group = OneToOneField('group')  # used for permission checking

class WallPost(model):
  wall = ForeignKey('wall')
  # content, author, time ...

# use for store
class Store(model):
  wall = OneToOneField('wall')

# use for group
class Group(model):
  wall = OneToOneField('wall')
```

All permission checks can query `wall.group`, regardless if the wall is for stores or for groups.

This then allows us to build a `/api/wall-posts/` endpoint with the following behaviour:
- `post(data={ wall: 77 })` - create a new post in wall 77
- `get /api/wall-posts/?wall=77` - get all posts in wall 77

The wall ID is return in the group/store response.


Another consideration:
If we want to implement store teams, we should probably plan it before implementing the wall.
