### ISSUE TITLE
Send report on HTTP500

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#267]
Django should have some functionality to log HTTP500 with details and send out log messages.

**Comment by tiltec** [comment]
I just got the hint to have a look at http://sentry.io/ - does anybody have experience with it?

**Comment by nicksellen** [comment]
Nope. I used some similar things before. Are usually super simple to setup and can be useful. Go for it! Assuming it has a suitable free plan for us....

**Comment by tiltec** [comment]
Free plan has 10k events per month. Should be more than enough for the backend if we just log HTTP500.
If we want to use it for frontend errors as well, it could explode ;)
