### ISSUE TITLE
Search for user id?

### ISSUE THREAD

**Issue by nicco11a** [yunity/foodsaving-backend#273]
You can only search for the display name with the /users part of the API, missing the possibility to search for user IDs.

We want to use this function for a foodshare in Gothenburg (Göteborg) / Sweden in order  to notify the foodsavers via e-mail of available pickups that have not yet been taken by anyone etc. and without the option to search for particular user ID's in the /users part of the API we are forced to ask for a larger dataset then needed. This may impact system performance in a future with many foodsavers.

**Comment by tiltec** [comment]
Hi @nicco11a - I would like to understand your use case better. Currently, the backend is only developed for the foodsaving.world frontend. That means that the API is not stable and can change any time. If you would like to use the API with other clients, I would invite you to join our slack (slackin.yunity.org) to talk about the bigger plans.

About the specific issue: you can get individual user data by ID (/api/users/<id>/) or filter the users by group. What do you miss?

Besides that, I would like to have notifications built-in the backend. E.g. if there's a pickup up open 24 hours before it happens, it will notify all users. See here https://github.com/yunity/foodsaving-frontend/issues/257 for the feature discussion.

**Comment by nicco11a** [comment]
Thanks for your feedback about your plans for the notify function, your ideas about notify is great, but we got a customised notify with at least one instructor and 2 students when doing a pickup. It's because of how the concept of study circle works in Sweden and we get support from the study organisations, you can read more about it here:
https://en.wikipedia.org/wiki/Study_circle

Yes, we would also like to publish information about pickups on our webpage and Facebook, perhaps also Twitter in the future.. Time will tell, but using the API is the easiest way to do it and I think changes in the API model is easier to handle then resolving merge requests.

We would of course like a unctions pickups and join in information about the users, but since we got the study circle to think about we still need to keep track of who is the instructor and customise the e-mail's to them and therefore just asking for the user ID's. Of course a function that lists all users by group and merges the user data would also be useful, but I know you guys are busy and don't want to ask for too much.

**Comment by tiltec** [comment]
The study circle reminds me very much of the "Introductory pickups" system that foodsharing.de has in some regions. In Munich, there was usually also one instructor and two newcomers at one pickup. It's definitely on our roadmap to support this system in foodsaving worldwide.

Do you think you would be able to join our team and make this implementation for everyone?

**Comment by nicco11a** [comment]
It is interesting that the particular way of notifying is interesting for other groups, but this issue was about a way to search for a specific user id through the API backend and I did find out that this was documented in the docs part:
https://foodsaving.world/docs/#!/users

while it's not part of the API users documentation:
https://foodsaving.world/api/users/

I've logged #280 to sort out this.

We are a group of people who are considering to jump in as developers and I will discuss the details in Slack.

**Comment by nicco11a** [comment]
Added the concept of introductory pickups into the wishlist of 363 (yunity/foodsaving-frontend#363). Trying to summarize in one place so people can get a better overview of the feature needed.

**Comment by tiltec** [comment]
Can you close this if not needed anymore @nicco11a ? Hope the docs are going to be fixed :)
