### ISSUE TITLE
Save language for user

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#276]
To enable the frontend to remember the users' language, even when logging in on a different browser/device.

TODO:

- new optional field in user model
- add field to serializer
- adapt/extend tests

**Comment by barryjohnthompson** [comment]
Hi! I'd like to try this one, if that's OK? This would be my first commit so I might need some help along the way. I would need a few days to get familiar with the code base, but on first look:

- In /users/models.py
** Add languages to the` _create_user` function and to the `User` class

- In /users/serializers.py
** Add languages to the `fields` list in the `Meta` class (and also the `extra_kwargs` dict?)
** Add languages to the `update` function? (may be outside the scope of this issue?)

- Add appropriate tests to /users/tests test_model.py and test_serializer.py

Does this sound roughly correct? 
Thanks :)

**Comment by tiltec** [comment]
That sounds about right. I think you don't need to modify the `create_user` method, instead use a default value of "English". You can also leave away the extra_kwargs in the serializer.

I think you need to modify the update function as well, otherwise the user won't be able to change their language.

How would you keep the language? Maybe as strings? `en`, `de`

**Comment by barryjohnthompson** [comment]
Thanks for your reply! I'll need to look at the code base properly but strings sounds like a sensible way of doing it. I'll have a go at this over the weekend and hopefully have a PR soon :)
