### ISSUE TITLE
API documentation needs update

### ISSUE THREAD

**Issue by nicco11a** [yunity/foodsaving-backend#280]
The API documentation is not in sync, for example in the user API call /users only describes the option to search for a display_name:
https://foodsaving.world/api/users/
 
While the docs users section describes 8 more functions:
https://foodsaving.world/docs/#!/users

The result of this was that I logged #273 did not think there was a way to search for a user id while it was as easy as specifying /users/{id}/.

**Comment by tiltec** [comment]
I would not use the DRF API explorer (https://foodsaving.world/api/users/), it has limited functionality compared to Swagger (/docs). Maybe we should disable it?

The information in Swagger also needs updating, especially the data that is generated from the serializer.

**Comment by nicco11a** [comment]
How about just presenting a short text that the documentation is on Swagger
with the link available?
https://foodsaving.world/docs/

**Comment by tiltec** [comment]
That would need some hacks. /api comes from the Django REST Framework, it determines the content type and delivers an appropriate response.
Example: `https://foodsaving.world/api/users/?format=json` gives you json, while `https://foodsaving.world/api/users/?format=api` gives you the browser.

Here's more documentation on the API renderer: http://www.django-rest-framework.org/topics/browsable-api/
And here's more on API documentation generally: http://www.django-rest-framework.org/topics/documenting-your-api/

These renderers are available in DRF: http://www.django-rest-framework.org/api-guide/renderers/
We could either modify the built-in `BrowsableAPIRenderer` and `AdminRenderer` or use a static template to redirect the users to Swagger.

**Comment by nicco11a** [comment]
Well, adding the link as static content like, "for a more extensive
documentation of the API see ..." would be sufficient I think.

**Comment by tiltec** [comment]
I think so too.

**Comment by nicco11a** [comment]
Adding something about Swagger API documentation on the foodsaving-backend repository readme:
https://github.com/yunity/foodsaving-backend

Maybe some blog post and the wiki pages needs a update too..
