### ISSUE TITLE
implement an image upload in backend

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/foodsaving-backend#55]
An image upload needs:
a) get the image from the user. Ideally, there would be an interface available for showing upload progress. (optional - extract to extra task if not implemented with this)
b) upload and - optionally dependent on usage - resize the file accordingly
c) think about storing all available images with metadata in db to link them to users and usage

**Comment by tiltec** [comment]
linked to #32

**Comment by NerdyProjects** [comment]
linked to #137

**Comment by tiltec** [comment]
Implement this for food basket pictures.

**Comment by dguitarbite** [comment]
so shall I take this over?

**Comment by raphaelfellmer** [comment]
yeahh!

--
"Never doubt that a small group of thoughtful, committed, citizens can
change the world. Indeed, it is the only thing that ever has." Margaret Mead

*www.yunity.org <http://www.yunity.org> Multi-sharing and saving Platform -
Join now!*

*"Glücklich ohne Geld!
<http://www.raphaelfellmer.de/buch-gluecklich-ohne-geld/>" als eBook
kostenlos herunterladen*
*www.raphaelfellmer.de <http://www.raphaelfellmer.de>*

**Comment by NerdyProjects** [comment]
I would suggest, check the system out, see how you like the attached proposal software use. Seems like we should write down requirements first. Would take a bit of time until done, but you may also do proposals.

For the start:
- We expect all of yunity software running and runnable on a single, user controlled server at the beginning. So please don't use any external services.
- The environment already contains nodejs and python. If there are no good reasons, please don't introduce new technology into this stack, but you might
- Typical use case will be about 100000 profile pictures and 50000 additional pictures, 1000 coming in every day
- Pictures will be needed for multiple things, e.g. 75x100 px avatar, 75x75 px item basket preview, 300x300px basket details (just example values)
- The API should offer a common possibility to upload those pictures that can then be used for different things, e.g. providing an ID for each upload, that does not have to be targeted to something before, sounds reasonable (this would also completely abstract the resizing process)
- For a future use, image upload may be outsourced to some other service, either self hosted or via a service provider, that may mean that we can, if it makes sense, just provide a java script API instead of a HTTP API for uploading so we can abstract on that layer.

We can either together design an architecture around this that would provide all of this, or not.

**Comment by tiltec** [comment]
Required for profile pictures: https://trello.com/c/d6p44LvP/52-u-2-as-a-user-i-want-to-view-and-edit-my-profile-so-that-i-can-tell-something-about-me-story-points

**Comment by dguitarbite** [comment]
@tiltec I would like to push this as my first patch to yunity :D ...

**Comment by tiltec** [comment]
http://www.django-rest-framework.org/api-guide/fields/#imagefield  with [Pillow](https://pillow.readthedocs.io/en/3.3.x/index.html) might be an option.

**Comment by tiltec** [comment]
Had a look in https://django-versatileimagefield.readthedocs.io/en/latest/using_sizers_and_filters.html seemed pretty ok.

**Comment by tiltec** [comment]
Not needed right now. Would be nice to have, but the page is usable without.
